create database bd_lista_moios;

-- TABLA USUARIO
CREATE TABLE USUARIO(
    NICKNAME VARCHAR(20),
    NOMBRE_APELLIDO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(10) NOT NULL,
    PRIMARY KEY(NICKNAME)
    );

-- tabla genero
CREATE TABLE GENERO(
    ID INT AUTO_INCREMENT,
    DESCRIPCION VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID)
);

-- TABLA CANCION
CREATE TABLE CANCION(
    ID INT AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    AUTOR VARCHAR(100),
    NICKNAME VARCHAR(20),
    GENERO_ID INT,
    PRIMARY KEY(ID)
);

ALTER TABLE CANCION ADD CONSTRAINT fk_cancion_usuario
FOREIGN KEY(NICKNAME) REFERENCES USUARIO(NICKNAME);

ALTER TABLE CANCION ADD CONSTRAINT fk_cancion_genero
FOREIGN KEY(GENERO_ID) REFERENCES GENERO(ID);

CREATE TABLE LISTA_REPRODUCCION(
    ID INT AUTO_INCREMENT,
    DESCRIPCION VARCHAR(100),
    NICKNAME VARCHAR(20),
    PRIMARY KEY(ID)
);

ALTER TABLE LISTA_REPRODUCCION ADD CONSTRAINT fk_lista_usuario
FOREIGN KEY(NICKNAME) REFERENCES USUARIO(NICKNAME);

--TABLA LISTA_CANCION
CREATE TABLE LISTA_CANCION(
    LISTA_ID INT,
    CANCION_ID INT
);

ALTER TABLE LISTA_CANCION ADD CONSTRAINT pk_lista_cancion
PRIMARY KEY(LISTA_ID, CANCION_ID);

ALTER TABLE LISTA_CANCION ADD CONSTRAINT fk_listac_listar
FOREIGN KEY(LISTA_ID) REFERENCES LISTA_REPRODUCCION(ID);

ALTER TABLE LISTA_CANCION ADD CONSTRAINT fk_listac_cancion
FOREIGN KEY(CANCION_ID) REFERENCES CANCION(ID);

-- INSERTAR USUARIO 
INSERT INTO USUARIO VALUES("moios","moi at","m@g.com","12345");

INSERT INTO USUARIO(nickname,password,nombre_apellido,email)
values("pepe","12345","pepe at","p@g.com");

-- UPDATE
update USUARIO
set password = "1111" where nickname = "pepe";

-- INSERT
insert into Genero values(default, "ROCK PARAGUAYO"); -- 1
insert into Genero values(default, "PUNK ROCK PARAGUAYO"); -- 2
insert into Genero (descripcion) values("trap");
insert into CANCION values (default, "Tanto y Nada", "FLOU","moios",1);

insert into CANCION
values(default, "Aqui Estoy","Area 69","pepe,"
(select id from genero where descripcion = "PUNK ROCK PARAGUAYO"));


-- select
SELECT * FROM USUARIO;
SELECT EMAIL FROM USUARIO WHERE nickname like "moios";

SELECT UPPER(C.NOMBRE) "TEMA", C.AUTOR, G.DESCRIPCION "GENERO" FROM CANCION C JOIN GENERO G
ON C.GENERO_ID = G.ID
WHERE C.NICKNAME LIKE "moios";